import { databaseStatus } from '../config/supabase.js'
import { createConversation, deleteConversation, getConversation, listConversations } from '../services/conversationService.js'
import { transcribeAudio } from '../services/speechToTextService.js'
import { translateTranscript } from '../services/translationService.js'
import { analyzeIntent } from '../services/intentAnalysisService.js'
import { summarize } from '../services/summarizationService.js'
import { getModelBenchmark } from '../services/evaluationMetricsService.js'

const ok = (res, data, meta={}) => res.json({ success:true, data, meta })
export const status = (req,res) => ok(res, databaseStatus())
export const list = async (req,res) => ok(res, await listConversations(), { database:databaseStatus() })
export const detail = async (req,res) => { const item = await getConversation(req.params.id); if (!item) return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Conversation not found.'}}); return ok(res,item,{database:databaseStatus()}) }
export const create = async (req,res) => ok(res, await createConversation(req.body), { database:databaseStatus() })
export const remove = async (req,res) => { const removed = await deleteConversation(req.params.id); if (!removed) return res.status(404).json({success:false,error:{code:'NOT_FOUND',message:'Conversation not found.'}}); return ok(res,{id:req.params.id}) }
export const processRecording = async (req,res) => {
  const benchmark = getModelBenchmark(req.body.speech_model)
  const speech = await transcribeAudio(req.body.audio, benchmark.id)
  const translation = await translateTranscript(speech.transcript, req.body.target_language)
  return ok(res,{transcript:speech.transcript,translated_transcript:translation.transcript,model:benchmark},{processing:'mock',message:'Demo transcript, translation, and evaluation metrics were generated by mock adapters.'})
}
export const generateInsights = async (req,res) => {
  const [summary,intent] = await Promise.all([summarize(req.body.transcript),analyzeIntent(req.body.transcript)])
  return ok(res,{summary:summary.summary,key_points:summary.key_points,intent:intent.intent,topics:intent.topics},{processing:'mock',message:'Demo insights were generated by mock adapters.'})
}
